/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.1.2   2017-09-27

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Private macro */


#include "utils.h"

void startup(void);
void lcd_flush_write(uint8_t col_num, uint8_t row_num, char* msg);
void check_state(void);

char * lcd_str;
int8_t currentState_next, currentState_set, currentState_prev;
int8_t prevState_next, prevState_set, prevState_prev;
int8_t currMode, potVal;
char potVal_str[32];
int8_t mode_potVal[4];

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

  startup();

  /* Infinite loop */
  while (1)
  {
	  //Update Screen
	  lcd_flush_write(0, 0, lcd_str);

	  potVal = adc_convert();
	  sprintf(potVal_str, "%d", potVal);
	  strcat(potVal_str, "%");
	  TM_HD44780_Puts(5, 1, potVal_str);

	  //Check buttons
	  currentState_next = GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_7);
	  currentState_set = GPIO_ReadInputDataBit (GPIOA, GPIO_Pin_2);
	  currentState_prev = GPIO_ReadInputDataBit (GPIOA, GPIO_Pin_3);

	  //Check button Next
	  if ( (currentState_next == Bit_SET) && (prevState_next != Bit_SET) ){
		  if (++currMode > 4) {
			  currMode = MODE_SHIFT;
		  }
		  check_state();


	  }

	  //check button set
	  if ( (currentState_set == Bit_SET) && (prevState_set != Bit_SET) ){
		  lcd_str = "Set!";
		  mode_potVal[currMode] = potVal;
	  }

	  if ( (currentState_prev == Bit_SET) && (prevState_prev != Bit_SET) ){

		  if (--currMode < 0) {
			  currMode = VOLUME;
		  }
		  check_state();

	  }
	  //Check button set

	  delay_ms(200);
	  prevState_next = currentState_next;
	  prevState_set = currentState_set;
	  prevState_prev = currentState_prev;
  }
}

void lcd_flush_write(uint8_t col_num, uint8_t row_num, char* msg){
	TM_HD44780_Clear();
	TM_HD44780_Puts(col_num,row_num,msg);
}

void startup(void) {
	config();
	//freqShift.lcdStr = "Frequency Shift"; autoTune.lcdStr = "Auto tune"; reverb.lcdStr = "Reverb"; echo.lcdStr = "Echo"; volume.lcdStr = "Volume";
	TM_HD44780_Init(LCD_COLUMNS, LCD_ROWS);
	TM_HD44780_Puts(4, 0, "tuneME");
	TM_HD44780_Puts(3, 1, "Welcome!");
	TM_HD44780_BlinkOn();
	delay_ms(5000);
	TM_HD44780_BlinkOff();
	//_modes[0] = freqShift;_modes[1] = autoTune;_modes[2] = reverb; _modes[3] = echo;_modes[4] = volume;
	currMode = MODE_SHIFT;
	prevState_next = prevState_set = prevState_prev = 0;
	lcd_str = "Frequency Shift";
}

void check_state() {

	if (currMode == MODE_SHIFT) {
		lcd_str = "Frequency Shift";
	}
	if (currMode == MODE_AUTOTUNE) {
		lcd_str = "Auto Tune";
	}
	if (currMode == MODE_REVERB) {
		lcd_str = "Reverb";
	}
	if (currMode == MODE_ECHO) {
		lcd_str = "Echo";
	}
	if (currMode == VOLUME) {
		lcd_str = "Volume";
	}
}

/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
  /* TODO, implement your code here */
  return;
}


/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
  /* TODO, implement your code here */
  return -1;
}


